import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "@/providers/Session.provider";
import { getUser } from "@/lib/lucia";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await getUser();
  console.log(sessionData);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <SessionProvider value={sessionData}>{children}</SessionProvider>
      </body>
      <Toaster richColors />
    </html>
  );
}
